- command: pwd
  register: pwd
- name: make all
  docker_image:
      state: build
      name: "{{ item.name }}"
      docker_api_version: 1.18
      dockerfile: build/test/{{ item.name }}.Dockerfile
      path: "{{ pwd.stdout }}"
  with_items: "{{ images }}"
  tags: 
  - build

- name: stop all
  docker:
      name: "{{ item.name }}"
      state: stopped
      image: "{{ item.name }}"
      docker_api_version: 1.18
      stop_timeout: 2
  with_items: "{{ images }}"
  tags:
  - stop

- name: start all
  docker: 
      name: "{{ item.name }}"
      image: "{{ item.name }}"
      docker_api_version: 1.18
      state: started
      net: bridge
      links: "{{ item.links  }}"
      volumes: [ "{{ pwd.stdout }}/:/opt/gondul" ]
  with_items: "{{ images }}"
  tags: 
  - start
- name: workaround to get gondul-varnish-front-ip
  shell: "docker inspect gondul-varnish | grep IPAddress | sed 's/[^0-9.]//g'"
  register: ip
  tags:
  - start
- name: workaround to get gondul-front-ip
  shell: "docker inspect gondul-front | grep IPAddress | sed 's/[^0-9.]//g'"
  register: ipfront
  tags:
  - start

- name: Display IP
  tags:
  - start
  debug:
    msg: "Varnish test is available at http://{{ ip.stdout }}/ uncached ip: http://{{ ipfront.stdout }}/ "

