---
- hosts: all
  become: false
  roles:
    - basics
    - test
  vars:
  - images:
    - name: "nms-db-test"
      links: []
    - name: "nms-front-test"
      links: [ "nms-db-test:db" ]
    - name: "nms-varnish-test"
      links: [ "nms-front-test:nms-front" ]
    - name: "nms-collector-test"
      links: [ "nms-db-test:db" ]
    - name: "nms-snmp-test"
      links: [ "nms-db-test:db" ]
