---
- hosts: all
  become: false
  roles:
    - basics
    - test
  vars:
  - images:
    - name: "gondul-db-test"
      links: []
      ports: []
    - name: "gondul-front-test"
      links: [ "gondul-db-test:db" ]
      ports: "{{ front_ports }}"
    - name: "gondul-varnish-test"
      links: [ "gondul-front-test:gondul-front" ]
      ports: "{{ varnish_ports }}"
    - name: "gondul-collector-test"
      links: [ "gondul-db-test:db" ]
      ports: []
    - name: "gondul-snmp-test"
      links: [ "gondul-db-test:db" ]
      ports: []
