---
- name: restart apache
  systemd:
    state: restarted
    daemon_reload: yes
    name: apache2

- name: restart varnish
  systemd:
    state: restarted
    daemon_reload: yes
    name: varnish

- name: reload systemd
  systemd:
    daemon_reload: yes